/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BucketSchools": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "EddiApp": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "GeminiAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MicrosoftClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MicrosoftClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MicrosoftTenantID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NomicAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "WebhookNotificationsOnboarding": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}