export const steps = {
	times: {
		percentage: 11,
		url: 'times',
		label: 'Times',
		previous: null,
		next: 'subjects',
	},
	subjects: {
		percentage: 22,
		url: 'subjects',
		label: 'Subjects',
		previous: 'times',
		next: 'teachers',
	},
	teachers: {
		percentage: 33,
		url: 'teachers',
		label: 'Teachers',
		previous: 'subjects',
		next: 'studentgroups',
	},
	studentgroups: {
		percentage: 44,
		url: 'studentgroups',
		label: 'Student Groups',
		previous: 'teachers',
		next: 'locations',
	},
	locations: {
		percentage: 55,
		url: 'locations',
		label: 'Locations',
		previous: 'studentgroups',
		next: 'activities',
	},
	activities: {
		percentage: 66,
		url: 'activities',
		label: 'Activities',
		previous: 'locations',
		next: 'constraints',
	},
	constraints: {
		percentage: 77,
		url: 'constraints',
		label: 'Constraints',
		previous: 'activities',
		next: 'generate',
	},
	generate: {
		percentage: 88,
		url: 'generate',
		label: 'Generate',
		previous: 'constraints',
		next: 'result',
	},
	result: {
		percentage: 100,
		url: 'result',
		label: 'Result',
		previous: 'generate',
		next: null,
	},
};
